#! /usr/bin/python3.7
import time, random, sys, subprocess

def pr(ch):
	print(f"{ch}",end="")
	sys.stdout.flush()
	a = random.randint(1,4) / 6
	time.sleep(a)

subprocess.run(['clear'])
time.sleep(3)
wake = "Wake up, Neo..."
for letter in wake:
	pr(letter)

time.sleep(3)
subprocess.run(['clear'])
matrix = "The Matrix has you..."
for letters in matrix:
	pr(letters)

time.sleep(2)
subprocess.run(['clear'])

rabbit = "Follow the white rabbit..."
for letters in rabbit:
	print(f"{letters}",end="")
	sys.stdout.flush()
	time.sleep(.05)

time.sleep(3)
subprocess.run(['clear'])
print("Knock, knock Neo.")
time.sleep(2)
subprocess.run(['clear'])
time.sleep(3)
